// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNFlA3MZhtlUXwsGxR_XhKc3DNius88H4',
    appId: '1:140493017436:web:defd6a8c883701b8c1f199',
    messagingSenderId: '140493017436',
    projectId: 'errandito2026',
    authDomain: 'errandito2026.firebaseapp.com',
    storageBucket: 'errandito2026.firebasestorage.app',
    measurementId: 'G-VREP4GC6ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOveSo1Uvjk2pHjYL9KKYxKmYfgaOYOE8',
    appId: '1:140493017436:android:7a3d62bbadca85a0c1f199',
    messagingSenderId: '140493017436',
    projectId: 'errandito2026',
    storageBucket: 'errandito2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPgVSlqV_DMVKbo6tfC1OvhZ_6AH2GCB4',
    appId: '1:140493017436:ios:abaf2eab6bc592ebc1f199',
    messagingSenderId: '140493017436',
    projectId: 'errandito2026',
    storageBucket: 'errandito2026.firebasestorage.app',
    iosBundleId: 'com.example.errandito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPgVSlqV_DMVKbo6tfC1OvhZ_6AH2GCB4',
    appId: '1:140493017436:ios:abaf2eab6bc592ebc1f199',
    messagingSenderId: '140493017436',
    projectId: 'errandito2026',
    storageBucket: 'errandito2026.firebasestorage.app',
    iosBundleId: 'com.example.errandito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNFlA3MZhtlUXwsGxR_XhKc3DNius88H4',
    appId: '1:140493017436:web:1e8a43eedb801ff4c1f199',
    messagingSenderId: '140493017436',
    projectId: 'errandito2026',
    authDomain: 'errandito2026.firebaseapp.com',
    storageBucket: 'errandito2026.firebasestorage.app',
    measurementId: 'G-T32Y422CSR',
  );

}